AWS_ACCESS_KEY = 'YOUR_AWS_ACCESS_KEY'
AWS_SECRET_KEY = 'YOUR_AWS_SECRET_KEY'

MASKS_READ_ONLY_AWS_ACCESS_KEY = 'YOUR_MASKS_READ_ONLY_AWS_ACCESS_KEY'
MASKS_READ_ONLY_AWS_SECRET_KEY = 'YOUR_MASKS_READ_ONLY_AWS_SECRET_KEY'
